name: record_linux
description: Patched Linux stub for record package (Android builds only)
version: 0.7.2

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  record_platform_interface: ^1.6.0

flutter:
  plugin:
    implements: record
    platforms:
      linux:
        dartPluginClass: RecordLinux
        fileName: record_linux.dart
