org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=33909 -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=33909 -Djdk.http.auth.tunneling.disabledSchemes= -Djdk.http.auth.proxying.disabledSchemes=
android.useAndroidX=true
android.enableJetifier=false
android.defaults.buildfeatures.buildconfig=true
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=33909
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=33909
